// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsAlwaysOnTop():Promise<boolean>;

export function ToggleAlwaysOnTop():Promise<boolean>;
