// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportHistory(arg1:string):Promise<void>;

export function ImportHistory():Promise<string>;

export function IsAlwaysOnTop():Promise<boolean>;

export function SaveHistory(arg1:string):Promise<void>;

export function ToggleAlwaysOnTop():Promise<boolean>;
