// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates(arg1) {
  return window['go']['main']['App']['CheckForUpdates'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function ExportHistory(arg1) {
  return window['go']['main']['App']['ExportHistory'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function ImportHistory() {
  return window['go']['main']['App']['ImportHistory']();
}

export function IsAlwaysOnTop() {
  return window['go']['main']['App']['IsAlwaysOnTop']();
}

export function SaveHistory(arg1) {
  return window['go']['main']['App']['SaveHistory'](arg1);
}

export function ToggleAlwaysOnTop() {
  return window['go']['main']['App']['ToggleAlwaysOnTop']();
}
