// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsAlwaysOnTop() {
  return window['go']['main']['App']['IsAlwaysOnTop']();
}

export function ToggleAlwaysOnTop() {
  return window['go']['main']['App']['ToggleAlwaysOnTop']();
}
