// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates(arg1:string):Promise<main.UpdateInfo>;

export function DownloadUpdate(arg1:string):Promise<void>;

export function ExportHistory(arg1:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function ImportHistory():Promise<string>;

export function IsAlwaysOnTop():Promise<boolean>;

export function SaveHistory(arg1:string):Promise<void>;

export function ToggleAlwaysOnTop():Promise<boolean>;
